---
title: "About"
author: "P8105 Final Project"
date: "11/11/2021"
output: html_document
---

# Team registration and proposal

## Group Members
The group members (names and UNIs)
Yang Gao (yg2762), Jiacheng Wu (jw4183), Wentong Liu (wl2829), Yueran Zhang (yz4188), Yuxuan Li (yl4928)

## The tentative project title
“Inspection for restaurants in New York City”

## The motivation for this project
With the untold restaurants throughout NYC, it can be a challenge to locate the “best” restaurants with particular location and specified cuisine. Our project mainly focuses on restaurant distribution in NYC with the objectives of classifying restaurants based on grades and cuisine descriptions and making a visualizable restaurant inspection. Since smartphone use is popular, we would like to create a web-based overview of restaurants in NYC for people to choose their next dine-in restaurant in a more efficient way. 

## The intended final products
Map of restaurant distribution in NYC based on grade and cuisine description. 
Other analyses on various common questions about restaurants in NYC.

## The anticipated data sources
DOHMH New York City Restaurant Inspection Results https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/rs6k-p7g6 

## The planned analyses / visualizations / coding challenges
*In which area/borough would you most likely find a specific cuisine?
*How are the restaurants with high/medium/low grades distributed in NYC?
*How are the restaurants with specified cuisine distributed in NYC? 
## The planned timeline

*Nov 11: proposal

*Nov 18: meet with teaching lead

*Data tidying
*Data wrangling
*Making plots
*Website outlook
*Writing descriptions, findings, discussion

*Dec 11: report & webpage overview

